DOLIBARR_BASE_URL={{DOLIBARR_BASE_URL}}
DOLIBARR_API_URL={{DOLIBARR_API_URL}}
DOLIBARR_API_KEY={{DOLIBARR_API_KEY}}
DOLIBARR_ENTITY={{DOLIBARR_ENTITY}}

MCP_PUBLIC_URL={{MCP_PUBLIC_URL}}
MCP_PORT={{MCP_PORT}}
MCP_READ_ONLY=true
MCP_LOG_LEVEL=info
MCP_ALLOWED_TOOLS={{MCP_ALLOWED_TOOLS}}
